#10 Sprint. Add friends likes
Semenem29/java-filmorate pull request #5
Opened 2023-08-24 17:38 UTC by Semenem29

Implementing features according 10th final task.

2023-08-25 16:49 UTC, Yang-Pi requested changes

2023-08-25 16:49 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    public void addFilm() {
Вот этот тестовый метод можно разделить на несколько. Старайся следовать принципу "single assert per method", те задача - писать модульный тест на максимально небольшой атомарный кусок бизнес-логики

2023-08-25 16:49 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleEmptyObjectPassingError(final NullPointerException e) {
Не, NPE - это в чистом виде 500. Но вообще это плохая практика мэтчить NPE к коду ошибки API-запроса, потому что NPE - это некая техническая ошибка, которая может возникать в рамках какого-то сценария, те NPE нужно обрабатывать в коде, но не в блоке try-catch, а в рамках if (... == null)

2023-08-25 16:49 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleFilmNotExistException(final FilmNotExistException e) {
Для упрощения можно сделать интерфейс или просто класс NotExistExcrption, и исключения вроде  FilmNotExistException и UserNotExistException унаследовать от этого класса, а в ErrorHandler обрабатывать NotExistExcrption вот этот тип

2023-08-25 16:49 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
О дублировании кода - сам по себе класс хранилища для обеих сущностей обладает одинаковым интерфейсом: add, getById, check, getAll. Поэтому можешь сделать дженерик интерфейс, вместо User/Film Storage.

2023-08-25 16:49 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            count = Integer.parseInt(NUMBER_OF_FILMS_IN_TOP_BY_DEFAULT);
Такую валидацию лучше внести в сервис и считать ошибкой неверных данных, потому что значение по-умолчанию используется для случаев, когда оно отсутствует в запросе в явном виде

2023-08-25 16:49 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User friend = getUsers().get(friendId);
На предыдущей строке ты уже получил пользователей, поэтому не нужно повторно обращаться к хранилищу.

2023-08-25 16:49 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User friend = getUsers().get(friendId);
Актуально и для остальных методов, где ты по несколько раз вызываешь метод get...()

2023-08-28 06:47 UTC, Semenem29 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            count = Integer.parseInt(NUMBER_OF_FILMS_IN_TOP_BY_DEFAULT);
done

2023-08-28 07:13 UTC, Semenem29 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleFilmNotExistException(final FilmNotExistException e) {
done

2023-08-28 07:13 UTC, Semenem29 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleEmptyObjectPassingError(final NullPointerException e) {
done

2023-08-28 07:57 UTC, Semenem29 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User friend = getUsers().get(friendId);
на предыдущей строке я получил не пользователей, а пользователя, поэтому еще раз обращаюсь к хранилищу, чтобы получить другого пользователя. просьба разъяснить комментарий

2023-08-28 09:16 UTC, Semenem29 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    public void addFilm() {
done

2023-08-28 09:56 UTC, Semenem29 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User friend = getUsers().get(friendId);
у меня есть в голове несколько вариантов решений, но ни один из них не выглядит лучше, чем этот. 
1. Создавать локальную мапу в каждом методе с гет и уже из нее вынимать User user и User friend, но в этом случае, я дублирую мапу, которая уже есть в хранилище и обращаюсь к ней два раза, вместо того, чтобы еще один дополнительный раз обратиться к хранилищу Storage<User> userStorage.
2. Создать глобальную мапу users, которую буду каждый раз обновлять в методах с гет, а потом уже из нее вынимать User user и User friend. Но опять же здесь дублирование уже существующей мапы, плюс операция обновления и те же запросы на получение 2 пользователей вместо одного дополнительного обращения к хранилищу.
3. с помощью функционального стиля, но здесь у меня нет идей как это реализовать. можно вынуть пользователй и собрать в список, в этом случае не будет заранее известно под каким индексом user, а под каким friend. Приходит в голову только такой громоздкий вариант, но назвать его элегантным решением не могу: 

        List<User> users = getUsers().values().stream()
                .filter(user -> user.getId().equals(userId) || user.getId().equals(friendId))
                .collect(Collectors.toList());

        Optional<User> user = users.stream()
                .filter(user1 -> user1.getId().equals(userId))
                .findFirst();

        Optional<User> friend = users.stream()
                .filter(user1 -> user1.getId().equals(friendId))
                .findFirst();

2023-08-28 18:53 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User friend = getUsers().get(friendId);
Я имел в виду все сильно проще - в рамках метода сделать переменную fetchedUsers (или usersFromRepository) и с ней работать. Те идея в том, чтобы в рамках одной транзакции не запрашивать одни и те же данные из бд.

2023-08-28 19:29 UTC, Semenem29 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User friend = getUsers().get(friendId);
готово. изменил логику в getCommonFriends(Integer userId, Integer friendId), removeFriend(Integer userId, Integer friendId) и addFriend(Integer userId, Integer friendId)

2023-08-28 19:56 UTC, Yang-Pi approved these changes

2023-09-06 15:51 UTC, merged